// packages/react/src/Shimmer.tsx
import React, { useLayoutEffect, useState, useRef } from 'react';
import { ShimmerProps } from './types';
import { useShimmerConfig } from './ShimmerContext';
import { extractElementInfo, type ElementInfo } from '@shimmer-from-structure/core';

/**
 * Shimmer component that adapts to the actual rendered structure of its children
 */
export const Shimmer: React.FC<ShimmerProps> = ({
  children,
  loading = true,
  shimmerColor,
  backgroundColor,
  duration,
  fallbackBorderRadius,
  templateProps,
}) => {
  // Get context values (contains defaults if no provider)
  const contextConfig = useShimmerConfig();

  // Merge: props > context > defaults
  const resolvedShimmerColor = shimmerColor ?? contextConfig.shimmerColor;
  const resolvedBackgroundColor = backgroundColor ?? contextConfig.backgroundColor;
  const resolvedDuration = duration ?? contextConfig.duration;
  const resolvedFallbackBorderRadius = fallbackBorderRadius ?? contextConfig.fallbackBorderRadius;

  const [elements, setElements] = useState<ElementInfo[]>([]);
  const contentRef = useRef<HTMLDivElement>(null);
  const measureRef = useRef<HTMLDivElement>(null);

  // Prepare children with injected template props when loading
  const childrenToRender = React.useMemo(() => {
    // Only inject template props if loading and templateProps is provided
    if (!loading || !templateProps) {
      return children;
    }

    // Get the first child
    const childArray = React.Children.toArray(children);
    if (childArray.length === 0) {
      return children;
    }

    const firstChild = childArray[0];

    // Check if it's a valid React element that can receive props
    if (!React.isValidElement(firstChild)) {
      return children;
    }

    // Clone the first child with the template props spread onto it
    const clonedChild = React.cloneElement(firstChild, {
      ...templateProps,
    });

    // Return cloned first child + rest of children unchanged
    return [clonedChild, ...childArray.slice(1)];
  }, [children, loading, templateProps]);

  // Measure the structure using useLayoutEffect (synchronous, before paint)
  useLayoutEffect(() => {
    if (!loading || !measureRef.current) return;

    const container = measureRef.current;
    const containerRect = container.getBoundingClientRect();

    // Extract all element dimensions
    const extractedElements: ElementInfo[] = [];
    Array.from(container.children).forEach((child) => {
      extractedElements.push(...extractElementInfo(child, containerRect));
    });

    // eslint-disable-next-line
    setElements(extractedElements);
  }, [loading, childrenToRender]);

  if (!loading) {
    return <>{children}</>;
  }

  return (
    <div style={{ position: 'relative' }}>
      {/* Inject styles for hiding text while preserving backgrounds */}
      <style>{`
        .shimmer-measure-container * {
          color: transparent !important;
        }
        .shimmer-measure-container img,
        .shimmer-measure-container svg,
        .shimmer-measure-container video {
          opacity: 0;
        }
      `}</style>

      {/* Children rendered with transparent text but visible container backgrounds */}
      <div
        ref={measureRef}
        className="shimmer-measure-container"
        style={{
          pointerEvents: 'none',
        }}
        aria-hidden="true"
      >
        {childrenToRender}
      </div>

      {/* Shimmer overlay based on measured dimensions */}
      <div
        ref={contentRef}
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          overflow: 'hidden',
        }}
      >
        <style>{`
          @keyframes shimmer {
            0% {
              transform: translateX(-100%);
            }
            100% {
              transform: translateX(100%);
            }
          }
        `}</style>

        {elements.map((element, index) => (
          <div
            key={index}
            style={{
              position: 'absolute',
              left: `${element.x}px`,
              top: `${element.y}px`,
              width: `${element.width}px`,
              height: `${element.height}px`,
              backgroundColor: resolvedBackgroundColor,
              borderRadius:
                element.borderRadius === '0px'
                  ? `${resolvedFallbackBorderRadius}px`
                  : element.borderRadius,
              overflow: 'hidden',
            }}
          >
            <div
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
                background: `linear-gradient(90deg, transparent, ${resolvedShimmerColor}, transparent)`,
                animation: `shimmer ${resolvedDuration}s infinite`,
              }}
            />
          </div>
        ))}
      </div>
    </div>
  );
};

// packages/vue/src/Shimmer.vue
<template>
  <div v-if="!loading">
    <slot></slot>
  </div>
  <div v-else style="position: relative">
    <!-- Styles for hiding text -->
    <component :is="'style'">
      {{ measureStyles }}
    </component>

    <!-- Measure container with transparent text -->
    <div
      ref="measureRef"
      class="shimmer-measure-container"
      style="pointer-events: none"
      aria-hidden="true"
    >
      <slot :loading="true" v-bind="templateProps"></slot>
    </div>

    <!-- Shimmer overlay -->
    <div :style="overlayStyle">
      <component :is="'style'">
        {{ shimmerKeyframes }}
      </component>

      <div v-for="(element, index) in elements" :key="index" :style="getElementStyle(element)">
        <div :style="getShimmerStyle()"></div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, nextTick, watch } from 'vue';
import { extractElementInfo, type ElementInfo } from '@shimmer-from-structure/core';
import { useShimmerConfig } from './composables/useShimmerConfig';

interface Props {
  loading?: boolean;
  shimmerColor?: string;
  backgroundColor?: string;
  duration?: number;
  fallbackBorderRadius?: number;
  templateProps?: Record<string, unknown>;
}

const props = withDefaults(defineProps<Props>(), {
  loading: true,
});

const measureRef = ref<HTMLElement | null>(null);
const elements = ref<ElementInfo[]>([]);

// Get context values
const contextConfig = useShimmerConfig();

// Resolved configuration (props > context > defaults)
const resolvedShimmerColor = computed(() => props.shimmerColor ?? contextConfig.shimmerColor);
const resolvedBackgroundColor = computed(
  () => props.backgroundColor ?? contextConfig.backgroundColor
);
const resolvedDuration = computed(() => props.duration ?? contextConfig.duration);
const resolvedFallbackBorderRadius = computed(
  () => props.fallbackBorderRadius ?? contextConfig.fallbackBorderRadius
);

// Measurement logic
const measureElements = async () => {
  if (!props.loading || !measureRef.value) return;

  await nextTick();

  const container = measureRef.value;
  const containerRect = container.getBoundingClientRect();

  const extractedElements: ElementInfo[] = [];
  Array.from(container.children).forEach((child) => {
    extractedElements.push(...extractElementInfo(child, containerRect));
  });

  elements.value = extractedElements;
};

// Watch for loading state changes
watch(() => props.loading, measureElements, { immediate: true });

onMounted(measureElements);

// Computed styles
const measureStyles = computed(
  () => `
  .shimmer-measure-container * {
    color: transparent !important;
  }
  .shimmer-measure-container img,
  .shimmer-measure-container svg,
  .shimmer-measure-container video {
    opacity: 0;
  }
`
);

const shimmerKeyframes = computed(
  () => `
  @keyframes shimmer {
    0% {
      transform: translateX(-100%);
    }
    100% {
      transform: translateX(100%);
    }
  }
`
);

const overlayStyle = computed(() => ({
  position: 'absolute' as const,
  top: '0',
  left: '0',
  right: '0',
  bottom: '0',
  overflow: 'hidden',
}));

const getElementStyle = (element: ElementInfo) => ({
  position: 'absolute' as const,
  left: `${element.x}px`,
  top: `${element.y}px`,
  width: `${element.width}px`,
  height: `${element.height}px`,
  backgroundColor: resolvedBackgroundColor.value,
  borderRadius:
    element.borderRadius === '0px'
      ? `${resolvedFallbackBorderRadius.value}px`
      : element.borderRadius,
  overflow: 'hidden',
});

const getShimmerStyle = () => ({
  position: 'absolute' as const,
  top: '0',
  left: '0',
  width: '100%',
  height: '100%',
  background: `linear-gradient(90deg, transparent, ${resolvedShimmerColor.value}, transparent)`,
  animation: `shimmer ${resolvedDuration.value}s infinite`,
});
</script>
